-- Question bank and per-user seen-question tracking.
create table if not exists public.question_bank (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
  question_text text not null,
  options jsonb not null,
  correct_option smallint not null check (correct_option between 0 and 3),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint question_bank_options_len check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4)
);

create unique index if not exists question_bank_question_text_level_uidx
  on public.question_bank (level, md5(question_text));

create index if not exists question_bank_is_active_level_idx
  on public.question_bank (is_active, level);

create table if not exists public.user_seen_questions (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.question_bank(id) on delete cascade,
  seen_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, question_id)
);

create index if not exists user_seen_questions_seen_at_idx
  on public.user_seen_questions (user_id, seen_at desc);

-- Harden access so clients can only read active questions (without answers) via policies.
alter table public.question_bank enable row level security;
alter table public.user_seen_questions enable row level security;

-- Question bank answers must never be directly queryable from the client.
revoke all on table public.question_bank from anon, authenticated;
revoke all on table public.user_seen_questions from anon, authenticated;

drop policy if exists "Authenticated users can read active question bank" on public.question_bank;

-- Keep user_seen_questions inaccessible from direct client calls.

-- Enforce per-user visibility for test results as defense in depth.
alter table public.test_results enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'test_results' and policyname = 'Users can view own test results'
  ) then
    create policy "Users can view own test results"
      on public.test_results
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;
end
$$;
