window.APP_CONFIG = window.APP_CONFIG || {
  SUPABASE_URL: 'https://basesupa.genairus.ru',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbGZob3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2MDAwMDAwMDAsImV4cCI6MTkxNTM2MDAwMH0.eWIDhJGpK4wQndtEzgsYLxTNBFuzdraxQn0R7Ph53f0',
};
